import React from 'react';
import { Link } from 'react-router-dom';
import {
  ShieldCheck,
  Lock,
  Cpu,
  Database,
  CheckCircle2,
  FileCode2,
  Activity,
  ArrowRight,
} from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { TickerTape } from '../components/layout/TickerTape';
import { AurexLogo } from '../components/brand/AurexLogo';

export const Security: React.FC = () => {
  const trustLayers = [
    {
      layer: 'Layer 01',
      title: 'Zero Look-Ahead Bias Quarantine',
      icon: <ShieldCheck className="w-6 h-6 text-emerald-400" />,
      desc: 'Strict mathematical point-in-time state machine. Price data and corporate actions are chronologically air-gapped to prevent future leakage from polluting backtest alphas.',
      badge: 'Mathematically Verified',
    },
    {
      layer: 'Layer 02',
      title: 'Cryptographic Lineage Ledger',
      icon: <Lock className="w-6 h-6 text-cyan-400" />,
      desc: 'Every AI token generated by Aiden is hashed and bound to physical warehouse records in real-time, providing an unalterable audit trail for institutional compliance.',
      badge: 'SHA-256 Verifiable',
    },
    {
      layer: 'Layer 03',
      title: 'RAG Grounded Retrieval Barrier',
      icon: <Database className="w-6 h-6 text-lime-400" />,
      desc: 'AI recommendations operate strictly on structured catalog, pricing elasticity, and inventory graphs. If records do not verify, the model gracefully abstains.',
      badge: 'Deterministic Retrieval',
    },
    {
      layer: 'Layer 04',
      title: 'High-Throughput Analytics Core',
      icon: <Cpu className="w-6 h-6 text-amber-400" />,
      desc: 'DuckDB and Python vectorized engines executing queries with hardware-enforced memory isolation and zero shared state contention.',
      badge: 'Real-Time Runtime',

    },
    {
      layer: 'Layer 05',
      title: 'Institutional Access Governance (RBAC)',
      icon: <FileCode2 className="w-6 h-6 text-emerald-400" />,
      desc: 'Fine-grained attribute-based access control, cryptographic enclave execution, and single-tenant data segregation for high-stakes enterprise deployments.',
      badge: 'SOC2 Type II Ready',
    },
    {
      layer: 'Layer 06',
      title: 'Continuous Automated Auditability',
      icon: <Activity className="w-6 h-6 text-cyan-400" />,
      desc: 'Automated discrepancy monitors continuously reconcile simulation parameters against live broker feeds and transactional settlement records.',
      badge: 'Continuous Telemetry',
    },
  ];

  return (
    <div className="min-h-screen bg-obsidian-900 text-slate-100 font-sans overflow-x-hidden relative bg-grain">
      <Navbar />

      <main className="pt-32 pb-24 px-6 md:px-12 max-w-6xl mx-auto space-y-16">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <div className="mb-2 flex justify-center">
            <AurexLogo size={44} />
          </div>
          <span className="font-mono text-xs text-emerald-400 uppercase tracking-widest bg-emerald-500/10 px-3.5 py-1 rounded-full border border-emerald-500/20 font-semibold">
            Institutional Trust & Governance
          </span>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-sans font-bold text-white tracking-tight">
            The AUREX Trust Architecture
          </h1>
          <p className="text-slate-300 text-base leading-relaxed font-sans">
            Designed for high-stakes quantitative funds and global enterprise operators who cannot afford black-box AI hallucinations or look-ahead backtesting bias.
          </p>
        </div>

        {/* 6-Layer Interactive Trust Stack */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {trustLayers.map((tl, idx) => (
            <div
              key={idx}
              className="glass-card p-6 rounded-3xl border border-white/10 hover:border-white/20 transition-all flex flex-col justify-between group font-sans"
            >
              <div>
                <div className="flex items-center justify-between mb-4">
                  <div className="p-3 bg-obsidian-950 rounded-2xl border border-white/10 group-hover:border-lime-500/40 transition-colors">
                    {tl.icon}
                  </div>
                  <span className="font-mono text-xs text-slate-400 font-bold">{tl.layer}</span>
                </div>

                <h3 className="font-sans font-bold text-lg text-white mb-2">{tl.title}</h3>
                <p className="text-slate-300 text-xs leading-relaxed font-sans mb-6">{tl.desc}</p>
              </div>

              <div className="pt-4 border-t border-white/5 text-xs text-emerald-400 font-semibold flex items-center justify-between font-sans">
                <span>{tl.badge}</span>
                <CheckCircle2 className="w-4 h-4" />
              </div>
            </div>
          ))}
        </div>

        {/* Call to Action Bar */}
        <div className="glass-card p-8 rounded-3xl border border-lime-500/30 text-center space-y-4 max-w-2xl mx-auto shadow-lime-glow font-sans">
          <h3 className="font-sans font-bold text-2xl text-white">
            Ready to deploy enterprise-grade intelligence?
          </h3>
          <p className="text-slate-300 text-xs font-mono">
            Launch the AUREX Command Center with zero configuration.
          </p>
          <div className="pt-2">
            <Link
              to="/app/overview"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-lime-500 hover:bg-lime-400 text-obsidian-950 font-bold text-xs shadow-lime-glow transition-all font-sans"
            >
              <span>Launch Command Center</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </main>

      <TickerTape />
    </div>
  );
};
